# Generated by Django 5.0.6 on 2024-06-28 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(max_length=9, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='main.profesor'),
        ),
    ]
